version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install robotframework robotframework-seleniumlibrary selenium webdriver-manager
  pre_build:
    commands:
      - echo Pre-build stage...
  build:
    commands:
      - echo Starting tests...
      - robot --outputdir results tests/
cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '/usr/bin/google-chrome-stable'
    - '/usr/local/bin/chromedriver'
artifacts:
  files:
    - appspec.yml
    - results/**/*
  discard-paths: no