version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install robotframework robotframework-seleniumlibrary selenium
      - pip install chromedriver-binary==131.0.6778.85
      - wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_131.0.6778.85-1_amd64.deb
      - apt-get update && apt-get install -y ./google-chrome-stable_current_amd64.deb
  pre_build:
    commands:
      - echo Pre-build stage...
  build:
    commands:
      - robot --outputdir results tests/
cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '/usr/bin/google-chrome-stable'
    - '/usr/local/bin/chromedriver'
artifacts:
  files:
    - appspec.yml
    - results/**/*
  discard-paths: no
